=== manzamb/SemanticWebinAction/02 - XML - RDF/Solución XML/AppEjemploXML/Ejemplos 2/02-dtd/dtdcontactos2.dtd
<!ELEMENT ListaContactos2 (MiContacto)+>
  <!-- Elemento Raiz del árbol: 
       - Son obligatorios: nombre, apellidos
       - Es opcional (?): fecha_nacimiento
       - Se compone de 1 o más subelementos: se usa +
       - Se compone de 0 o más subelementos: correos-->
  <!ELEMENT MiContacto (Nombre+, Telefono+, Email?) >
  <!-- Estableciendo los tipos de datos de los elementos hoja de PERSONACONTACTO-->
  <!ELEMENT Nombre (#PCDATA)>
  <!ELEMENT Telefono (#PCDATA)>
  <!ELEMENT Email (#PCDATA)>

=== manzamb/SemanticWebinAction/02 - XML - RDF/Solución XML/AppEjemploXML/Ejemplos 2/03-xml/miscontactos2.xml
<?xml version="1.0" encoding="utf-8" ?>
<!-- <!DOCTYPE ListaContactos2 SYSTEM "../02-dtd/dtdcontactos2.dtd"> -->
<ListaContactos2 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
                xsi:noNamespaceSchemaLocation="../04-xsd/miscontactos2.xsd">
    <MiContacto>
        <Nombre>Jose Perez</Nombre>
        <Telefono>555-1234</Telefono>
        <Email>joseperez@hotmail.comorem.com</Email>
    </MiContacto>
    <MiContacto>
        <Nombre>Maria Lopez</Nombre>
        <Telefono>555-5678</Telefono>
        <Email>marialopez@hotmail.comorem.com</Email>
    </MiContacto>
    <MiContacto>
        <Nombre>Jorge Cerquera</Nombre>
        <Telefono>555-9876</Telefono>
        <Email>jcerquera@hotmail.comorem.com</Email>
    </MiContacto>
    <MiContacto>
        <Nombre>Carlos Diaz</Nombre>
        <Telefono>555-4321</Telefono>
        <Email>cadiaz@hotmail.comorem.com</Email>
    </MiContacto>
</ListaContactos2>
